### ISSUE TITLE
Crash in LLVM/LLPC running tests from the vkd3d-proton test suite

### ISSUE THREAD

**Issue by Oschowa** [GPUOpen-Drivers/llpc#1749]
Running the `buffer_feedback_instructions_sm51` test from the [vkd3d-proton](https://github.com/HansKristian-Work/vkd3d-proton) test suite on AMDVLK crashes on v-2022.Q1.3 and a latest `dev` branch debug build with the following backtrace:  

```
#2  0x00007ffff79af534 in abort () from /usr/lib/libc.so.6
#3  0x00007ffff37b32f2 in llvm::llvm_unreachable_internal (msg=0x7ffff4ec7ee8 "Unknown type!", file=0x7ffff4ec7508 "/home/cme/mesa/amdvlk-dev/drivers/llvm-project/llvm/lib/CodeGen/ValueTypes.cpp", line=532) at /home/cme/mesa/amdvlk-dev/drivers/llvm-project/llvm/lib/Support/ErrorHandling.cpp:209
#4  0x00007ffff1aa4549 in llvm::MVT::getVT (Ty=0x555556126870, HandleUnknown=false) at /home/cme/mesa/amdvlk-dev/drivers/llvm-project/llvm/lib/CodeGen/ValueTypes.cpp:532
#5  0x00007ffff1aa4710 in llvm::EVT::getEVT (Ty=0x555556126870, HandleUnknown=false) at /home/cme/mesa/amdvlk-dev/drivers/llvm-project/llvm/lib/CodeGen/ValueTypes.cpp:563
#6  0x00007ffff0b8a722 in llvm::SITargetLowering::getTgtMemIntrinsic (this=0x555555d64fa8, Info=..., CI=..., MF=..., IntrID=1957) at /home/cme/mesa/amdvlk-dev/drivers/llvm-project/llvm/lib/Target/AMDGPU/SIISelLowering.cpp:1168
#7  0x00007ffff123221b in llvm::SelectionDAGBuilder::visitTargetIntrinsic (this=0x555555dbd640, I=..., Intrinsic=1957) at /home/cme/mesa/amdvlk-dev/drivers/llvm-project/llvm/lib/CodeGen/SelectionDAG/SelectionDAGBuilder.cpp:4768
#8  0x00007ffff1238f54 in llvm::SelectionDAGBuilder::visitIntrinsicCall (this=0x555555dbd640, I=..., Intrinsic=1957) at /home/cme/mesa/amdvlk-dev/drivers/llvm-project/llvm/lib/CodeGen/SelectionDAG/SelectionDAGBuilder.cpp:5788
#9  0x00007ffff1249b51 in llvm::SelectionDAGBuilder::visitCall (this=0x555555dbd640, I=...) at /home/cme/mesa/amdvlk-dev/drivers/llvm-project/llvm/lib/CodeGen/SelectionDAG/SelectionDAGBuilder.cpp:8114
#10 0x00007ffff121a151 in llvm::SelectionDAGBuilder::visit (this=0x555555dbd640, Opcode=56, I=...) at /home/cme/mesa/amdvlk-dev/drivers/llvm-project/llvm/include/llvm/IR/Instruction.def:209
#11 0x00007ffff1219b21 in llvm::SelectionDAGBuilder::visit (this=0x555555dbd640, I=...) at /home/cme/mesa/amdvlk-dev/drivers/llvm-project/llvm/lib/CodeGen/SelectionDAG/SelectionDAGBuilder.cpp:1125
#12 0x00007ffff12f1c50 in llvm::SelectionDAGISel::SelectBasicBlock (this=0x555555c4e060, Begin=..., End=..., HadTailCall=@0x7fffffffabef: false) at /home/cme/mesa/amdvlk-dev/drivers/llvm-project/llvm/lib/CodeGen/SelectionDAG/SelectionDAGISel.cpp:715
#13 0x00007ffff12f6a4e in llvm::SelectionDAGISel::SelectAllBasicBlocks (this=0x555555c4e060, Fn=...) at /home/cme/mesa/amdvlk-dev/drivers/llvm-project/llvm/lib/CodeGen/SelectionDAG/SelectionDAGISel.cpp:1623
#14 0x00007ffff12f0890 in llvm::SelectionDAGISel::runOnMachineFunction (this=0x555555c4e060, mf=...) at /home/cme/mesa/amdvlk-dev/drivers/llvm-project/llvm/lib/CodeGen/SelectionDAG/SelectionDAGISel.cpp:507
#15 0x00007ffff0d1912c in AMDGPUDAGToDAGISel::runOnMachineFunction (this=0x555555c4e060, MF=...) at /home/cme/mesa/amdvlk-dev/drivers/llvm-project/llvm/lib/Target/AMDGPU/AMDGPUISelDAGToDAG.cpp:134
#16 0x00007ffff1786f5a in llvm::MachineFunctionPass::runOnFunction (this=0x555555c4e060, F=...) at /home/cme/mesa/amdvlk-dev/drivers/llvm-project/llvm/lib/CodeGen/MachineFunctionPass.cpp:72
#17 0x00007ffff36409e1 in llvm::FPPassManager::runOnFunction (this=0x5555558e5800, F=...) at /home/cme/mesa/amdvlk-dev/drivers/llvm-project/llvm/lib/IR/LegacyPassManager.cpp:1434
#18 0x00007ffff2bf845e in (anonymous namespace)::CGPassManager::RunPassOnSCC (this=0x555555ee7330, P=0x5555558e5800, CurSCC=..., CG=..., CallGraphUpToDate=@0x7fffffffb60f: true, DevirtualizedCall=@0x7fffffffb6bf: false) at /home/cme/mesa/amdvlk-dev/drivers/llvm-project/llvm/lib/Analysis/CallGraphSCCPass.cpp:182
#19 0x00007ffff2bf9483 in (anonymous namespace)::CGPassManager::RunAllPassesOnSCC (this=0x555555ee7330, CurSCC=..., CG=..., DevirtualizedCall=@0x7fffffffb6bf: false) at /home/cme/mesa/amdvlk-dev/drivers/llvm-project/llvm/lib/Analysis/CallGraphSCCPass.cpp:480
#20 0x00007ffff2bf977d in (anonymous namespace)::CGPassManager::runOnModule (this=0x555555ee7330, M=...) at /home/cme/mesa/amdvlk-dev/drivers/llvm-project/llvm/lib/Analysis/CallGraphSCCPass.cpp:545
#21 0x00007ffff3641078 in (anonymous namespace)::MPPassManager::runOnModule (this=0x555556046b10, M=...) at /home/cme/mesa/amdvlk-dev/drivers/llvm-project/llvm/lib/IR/LegacyPassManager.cpp:1549
#22 0x00007ffff363c468 in llvm::legacy::PassManagerImpl::run (this=0x5555560e0730, M=...) at /home/cme/mesa/amdvlk-dev/drivers/llvm-project/llvm/lib/IR/LegacyPassManager.cpp:539
#23 0x00007ffff364189d in llvm::legacy::PassManager::run (this=0x555555d505d0, M=...) at /home/cme/mesa/amdvlk-dev/drivers/llvm-project/llvm/lib/IR/LegacyPassManager.cpp:1676
#24 0x00007ffff083d86a in lgc::PipelineState::generateWithLegacyPassManager(std::unique_ptr<llvm::Module, std::default_delete<llvm::Module> >, llvm::raw_pwrite_stream&, std::function<unsigned int (llvm::Module const*, unsigned int, llvm::ArrayRef<llvm::ArrayRef<unsigned char> >)>, llvm::ArrayRef<llvm::Timer*>) (this=0x5555558ef410, pipelineModule=..., outStream=..., checkShaderCacheFunc=..., timers=...) at /home/cme/mesa/amdvlk-dev/drivers/llpc/lgc/state/Compiler.cpp:296
#25 0x00007ffff083ce7e in lgc::PipelineState::generate(std::unique_ptr<llvm::Module, std::default_delete<llvm::Module> >, llvm::raw_pwrite_stream&, std::function<unsigned int (llvm::Module const*, unsigned int, llvm::ArrayRef<llvm::ArrayRef<unsigned char> >)>, llvm::ArrayRef<llvm::Timer*>, bool) (this=0x5555558ef410, pipelineModule=..., outStream=..., checkShaderCacheFunc=..., timers=..., newPassManager=false) at /home/cme/mesa/amdvlk-dev/drivers/llpc/lgc/state/Compiler.cpp:190
#26 0x00007ffff0616bff in Llpc::Compiler::buildPipelineInternal (this=0x555555e57730, context=0x555555f92bc0, shaderInfo=..., unlinked=false, pipelineElf=0x7fffffffca00, stageCacheAccesses=...) at /home/cme/mesa/amdvlk-dev/drivers/llpc/llpc/context/llpcCompiler.cpp:1032
#27 0x00007ffff0618805 in Llpc::Compiler::buildComputePipelineInternal (this=0x555555e57730, computeContext=0x7fffffffc860, pipelineInfo=0x7fffffffd3c0, buildingRelocatableElf=false, pipelineElf=0x7fffffffca00, stageCacheAccess=0x7fffffffd0d1) at /home/cme/mesa/amdvlk-dev/drivers/llpc/llpc/context/llpcCompiler.cpp:1384
#28 0x00007ffff0618e69 in Llpc::Compiler::BuildComputePipeline (this=0x555555e57730, pipelineInfo=0x7fffffffd3c0, pipelineOut=0x7fffffffd0c0, pipelineDumpFile=0x0) at /home/cme/mesa/amdvlk-dev/drivers/llpc/llpc/context/llpcCompiler.cpp:1443
#29 0x00007ffff0319b80 in vk::CompilerSolutionLlpc::CreateComputePipelineBinary (this=this@entry=0x555555f91fd8, pDevice=pDevice@entry=0x555555c59de8, deviceIdx=deviceIdx@entry=0, pPipelineCache=pPipelineCache@entry=0x555556207f10, pCreateInfo=pCreateInfo@entry=0x7fffffffd3c0, pPipelineBinarySize=pPipelineBinarySize@entry=0x7fffffffd5e0, ppPipelineBinary=0x7fffffffd5c0, pPipelineDumpHandle=0x0, pipelineHash=16814128156815565207, pCacheId=0x7fffffffd580, pCompileTime=0x7fffffffd208) at /home/cme/mesa/amdvlk-dev/drivers/xgl/icd/api/compiler_solution_llpc.cpp:354
#30 0x00007ffff0243dd5 in vk::PipelineCompiler::CreateComputePipelineBinary (this=0x555555f919b8, pDevice=pDevice@entry=0x555555c59de8, deviceIdx=deviceIdx@entry=0, pPipelineCache=pPipelineCache@entry=0x555556207f10, pCreateInfo=pCreateInfo@entry=0x7fffffffd3c0, pPipelineBinarySize=pPipelineBinarySize@entry=0x7fffffffd5e0, ppPipelineBinary=0x7fffffffd5c0, pCacheId=0x7fffffffd580) at /home/cme/mesa/amdvlk-dev/drivers/xgl/icd/api/pipeline_compiler.cpp:1338
#31 0x00007ffff0281c34 in vk::ComputePipeline::Create (pDevice=pDevice@entry=0x555555c59de8, pPipelineCache=pPipelineCache@entry=0x555556207f10, pCreateInfo=pCreateInfo@entry=0x7fffffffd7d0, pAllocator=pAllocator@entry=0x555555fb9af8, pPipeline=pPipeline@entry=0x555556200900) at /home/cme/mesa/amdvlk-dev/drivers/xgl/icd/api/vk_compute_pipeline.cpp:167
#32 0x00007ffff02a044c in vk::Device::CreateComputePipelines (this=0x555555c59de8, pipelineCache=0x555556207f10, count=1, pCreateInfos=0x7fffffffd7d0, pAllocator=0x555555fb9af8, pPipelines=0x555556200900) at /home/cme/mesa/amdvlk-dev/drivers/xgl/icd/api/vk_device.cpp:2561
#33 0x00007ffff02a345c in vk::entry::vkCreateComputePipelines (device=<optimized out>, pipelineCache=<optimized out>, createInfoCount=<optimized out>, pCreateInfos=<optimized out>, pAllocator=<optimized out>, pPipelines=<optimized out>) at /home/cme/mesa/amdvlk-dev/drivers/xgl/icd/api/vk_device.cpp:4030
#34 0x00007ffff7d4c2c3 in vkd3d_create_compute_pipeline (device=0x7fffed672010, code=0x7fffffffdac8, shader_interface=0x7fffffffd940, vk_pipeline_layout=0x5555561c7c40, vk_cache=0x555556207f10, vk_pipeline=0x555556200900, spirv_code=0x555556200908) at ../libs/vkd3d/state.c:2232
#35 0x00007ffff7d4c630 in d3d12_pipeline_state_init_compute (state=0x5555562008f0, device=0x7fffed672010, desc=0x7fffffffda70) at ../libs/vkd3d/state.c:2293
#36 0x00007ffff7d5076b in d3d12_pipeline_state_create (device=0x7fffed672010, bind_point=VK_PIPELINE_BIND_POINT_COMPUTE, desc=0x7fffffffda70, state=0x7fffffffda60) at ../libs/vkd3d/state.c:3650
#37 0x00007ffff7d18586 in d3d12_device_CreateComputePipelineState (iface=0x7fffed672010, desc=0x7fffffffde90, riid=0x555555700ee0 <IID_ID3D12PipelineState>, pipeline_state=0x7fffffffde88) at ../libs/vkd3d/device.c:2979
#38 0x000055555565bf49 in ID3D12Device_CreateComputePipelineState (This=0x7fffed672010, desc=0x7fffffffde90, riid=0x555555700ee0 <IID_ID3D12PipelineState>, pipeline_state=0x7fffffffde88) at libs/vkd3d-common/libvkd3d_common.a.p/vkd3d_d3d12.h:13670
#39 0x000055555566027f in create_compute_pipeline_state_ (line=1919, device=0x7fffed672010, root_signature=0x5555560193e0, cs=...) at ../tests/d3d12_test_utils.c:818
#40 0x0000555555619b8f in test_buffer_feedback_instructions (use_dxil=false) at ../tests/d3d12_sparse.c:1919
#41 0x000055555561a294 in test_buffer_feedback_instructions_sm51 () at ../tests/d3d12_sparse.c:2010
#42 0x000055555565846b in vkd3d_run_test (name=0x555555702f60 "test_buffer_feedback_instructions_sm51", test_pfn=0x55555561a286 <test_buffer_feedback_instructions_sm51>) at ../include/private/vkd3d_test.h:381
```

The test passes on amdgpu-pro 21.50.2, RADV and NVIDIA.
To reproduce:  
- clone the vkd3d-proton source: git clone --recurse-submodules https://github.com/HansKristian-Work/vkd3d-proton
- cd vkd3d-proton && mkdir build
- meson build -D enable_tests=true
- cd build && ninja
- cd tests
- run the specific tests: VKD3D_TEST_FILTER=buffer_feedback_instructions_sm51 ./d3d12

Thanks.

**Comment by perlfu** [comment]
[pipelines.zip](https://github.com/GPUOpen-Drivers/llpc/files/8349038/pipelines.zip)

The issue can be reproduced with the attached pipeline and command line compiler:
amdllpc -gfxip=10.1 PipelineCs_0x8CABCA3BC1E075D4.pipe

**Comment by perlfu** [comment]
Root cause seems to be missing TFE support for buffer.load.format intrinsics in LLVM AMDGPU backend.

**Comment by jinjianrong** [comment]
There are still some failures in the testing, but the crash is fixed
